# Generated by Django 3.0.7 on 2020-06-20 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliable',
            name='ids',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='busy',
            name='ids',
            field=models.CharField(default='', max_length=20),
        ),
    ]
